name: crud operation

on:
  push:
    branches: [main]

jobs:
  checkout_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: notify
        run: echo git clone done
  build_image_push_in_docker:
    runs-on: ubuntu-latest
    needs: [checkout_code]
    steps:
     - name: checkout code
       uses: actions/checkout@v3


     - name: login to docker
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     - name: create frontend image 
       uses: docker/build-push-action@v5
       with:
         context: ./Client
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/crud-frontend:latest
     - name: notify
       run: echo "frontend image push in dockerhub"